# -*- coding: utf-8 -*-
"""descargar_datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDXLNeTbxp6akhOYDsdAj_Ic5jN1RFr_
"""

import yfinance as yf
import matplotlib.pyplot as plt

fscope = open("scope.txt", "r")
scope = fscope.read(). splitlines()
fscope.close()

for activo in scope:

    datos = yf.Ticker("activo").history(period="2y")

    precio = datos["Close"]
    volumen = datos["Volume"]

    plt.figure(figsize=(12, 6))
    plt.plot(precio)
    plt.show()